-- MySQL Script generated by MySQL Workbench
-- Wed Oct 28 02:35:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Страны и города мира
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Страны и города мира
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Страны и города мира` DEFAULT CHARACTER SET utf8 ;
USE `Страны и города мира` ;

-- -----------------------------------------------------
-- Table `Страны и города мира`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Страны и города мира`.`Country` (
  `id_country` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_country`),
  UNIQUE INDEX `id_country_UNIQUE` (`id_country` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Страны и города мира`.`Region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Страны и города мира`.`Region` (
  `id_region` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `id_country` INT NOT NULL,
  PRIMARY KEY (`id_region`),
  UNIQUE INDEX `id_region_UNIQUE` (`id_region` ASC) VISIBLE,
  INDEX `Country_idx` (`id_country` ASC) VISIBLE,
  UNIQUE INDEX `id_country_UNIQUE` (`id_country` ASC) VISIBLE,
  CONSTRAINT `country`
    FOREIGN KEY (`id_country`)
    REFERENCES `Страны и города мира`.`Country` (`id_country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Страны и города мира`.`District`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Страны и города мира`.`District` (
  `id_district` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `id_region` INT NOT NULL,
  `id_country` INT NOT NULL,
  PRIMARY KEY (`id_district`),
  UNIQUE INDEX `iddistrict_UNIQUE` (`id_district` ASC) VISIBLE,
  INDEX `region_idx` (`id_region` ASC) VISIBLE,
  UNIQUE INDEX `id_region_UNIQUE` (`id_region` ASC) VISIBLE,
  UNIQUE INDEX `id_country_UNIQUE` (`id_country` ASC) VISIBLE,
  CONSTRAINT `region`
    FOREIGN KEY (`id_region`)
    REFERENCES `Страны и города мира`.`Region` (`id_region`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Страны и города мира`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Страны и города мира`.`City` (
  `id_city` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `id_region` INT NOT NULL,
  `id_country` INT NOT NULL,
  `id_district` INT NOT NULL,
  PRIMARY KEY (`id_city`),
  UNIQUE INDEX `id_city_UNIQUE` (`id_city` ASC) VISIBLE,
  UNIQUE INDEX `id_district_UNIQUE` (`id_district` ASC) VISIBLE,
  UNIQUE INDEX `id_region_UNIQUE` (`id_region` ASC) VISIBLE,
  UNIQUE INDEX `id_country_UNIQUE` (`id_country` ASC) VISIBLE,
  CONSTRAINT `district`
    FOREIGN KEY (`id_district`)
    REFERENCES `Страны и города мира`.`District` (`id_district`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
